<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="Zenseless.OpenTK" Version="0.1.98" />
    <EmbeddedResource Include="Content\**\*.*" />
    <None Update="Content\**\*.txt" />
  </ItemGroup>

</Project>
